# Generated by Django 3.2.4 on 2021-07-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('am_uid', models.AutoField(primary_key=True, serialize=False)),
                ('am_name', models.CharField(blank=True, max_length=100, null=True)),
                ('am_email', models.CharField(blank=True, max_length=100, null=True)),
                ('am_mobile', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'account_manager',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('am_name', models.CharField(blank=True, max_length=100, null=True)),
                ('am_email', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=5, null=True)),
                ('isstreak', models.BooleanField(blank=True, null=True)),
                ('isaddon', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('exchange_type', models.CharField(blank=True, max_length=25, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('isin', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('normalizer', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('am_uid', models.ForeignKey(blank=True, db_column='am_uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.accountmanager')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyQuote',
            fields=[
                ('company_ticker', models.OneToOneField(db_column='company_ticker', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.companyprofile')),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_quote',
            },
        ),
        migrations.CreateModel(
            name='FmpData',
            fields=[
                ('id', models.OneToOneField(blank=True, db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.company')),
                ('symbol', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=25, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('short_exchange', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'fmp_data',
            },
        ),
        migrations.CreateModel(
            name='IexData',
            fields=[
                ('id', models.OneToOneField(blank=True, db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.company')),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('cik', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange', models.CharField(blank=True, max_length=25, null=True)),
                ('securityname', models.CharField(blank=True, max_length=100, null=True)),
                ('securitytype', models.CharField(blank=True, max_length=5, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'iex_data',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdtv',
            fields=[
                ('company_ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('adtv', models.FloatField(blank=True, null=True)),
                ('adtv5', models.FloatField(blank=True, null=True)),
                ('adtv10', models.FloatField(blank=True, null=True)),
                ('adtv20', models.FloatField(blank=True, null=True)),
                ('adtv60', models.FloatField(blank=True, null=True)),
                ('adtv120', models.FloatField(blank=True, null=True)),
                ('isoutlier', models.BooleanField(blank=True, null=True)),
                ('aadtv', models.FloatField(blank=True, null=True)),
                ('aadtv5', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('aadtv10', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('aadtv20', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('aadtv60', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('aadtv120', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'company_adtv',
                'unique_together': {('company_ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompanyTrading',
            fields=[
                ('company_ticker', models.OneToOneField(db_column='company_ticker', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='company.companyprofile')),
                ('market_date', models.DateField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('change_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_trading',
                'unique_together': {('company_ticker', 'market_date')},
            },
        ),
    ]
