# Generated by Django 3.2.4 on 2021-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Manager',
            fields=[
                ('am_uid', models.AutoField(primary_key=True, serialize=False)),
                ('am_name', models.CharField(max_length=100)),
                ('am_email', models.CharField(max_length=100)),
                ('am_mobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddOnCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ticker', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('company_ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('exchange_type', models.CharField(max_length=25)),
                ('currency', models.CharField(max_length=5)),
                ('industry', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('normalizer', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_profile',
                'managed': False,
            },
        ),
    ]
