name: CI (Testing)

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - main
  release:
    types:
      - created
  schedule:
    - cron: '0 8 * * *'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Set up testing database
        run: |
          docker run \
            -d --name postgresql \
            -e POSTGRESQL_POSTGRES_PASSWORD=password123 \
            -e POSTGRESQL_USERNAME=river \
            -e POSTGRESQL_PASSWORD=fort \
            -e POSTGRESQL_DATABASE=riverFort \
            -p 5432:5432 \
            bitnami/postgresql:11.4.0

          pip install certifi==2021.5.30
          pip install chardet==4.0.0
          pip install idna==2.10
          pip install numpy==1.21.0
          pip install pandas==1.2.5
          pip install psycopg2==2.9.1
          pip install python-dateutil==2.8.1
          pip install pytz==2021.1
          pip install requests==2.25.1
          pip install six==1.16.0
          pip install urllib3==1.26.6

          python .github/workflows/testing_database.py

      - name: Coverage report
        env: 
          SECRET_KEY: om_8x$k00o5f-c=2v5fo#%rmwt8pmar_nzmmulj4hq%wn9q2^c
          ALLOWED_HOSTS: 127.0.0.1
          COMPANIES_DATABASE_ENGINE: postgresql_psycopg2
          COMPANIES_DATABASE_NAME: testing_database
          COMPANIES_DATABASE_USER: user
          COMPANIES_DATABASE_PASSWORD: password
          COMPANIES_DATABASE_HOST: 127.0.0.1
          COMPANIES_DATABASE_PORT: 5432
        run: |
          coverage run --omit='*/venv/*' manage.py test
          coverage report
