name: CI

on:
  push:
    branches: 
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions.setup-python@v2
        with:
          python-version: 3.8.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Coverage report
        run: |
          coverage run --omit='*/venv/*' manage.py test
          coverage report
      # - name: Testing
      #   run: |
      #     python manage.py test
