name: CI

on:
  push:
    branches: 
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Coverage report
        env: 
          SECRET_KEY: om_8x$k00o5f-c=2v5fo#%rmwt8pmar_nzmmulj4hq%wn9q2^c
          COMPANIES_DATABASE_ENGINE: postgresql_psycopg2
          COMPANIES_DATABASE_NAME: name
          COMPANIES_DATABASE_USER: user
          COMPANIES_DATABASE_PASSWORD: password
          COMPANIES_DATABASE_HOST: 127.0.0.1
          COMPANIES_DATABASE_PORT: 5432
        run: |
          pip install coverage
          coverage run --omit='*/venv/*' manage.py test
          coverage report
      # - name: Testing
      #   run: |
      #     python manage.py test
